// Project data — pulled from data.json with curated tags for voice filtering.
window.PORTFOLIO = {
  name: "Bill Zhang",
  tagline: "AI engineer. Builder of voice-first systems.",
  location: "Los Angeles, CA",
  email: "billzhang0011@gmail.com",
  github: "https://github.com/IdkwhatImD0ing",
  linkedin: "https://www.linkedin.com/in/bill-zhang1/",
  devpost: "https://devpost.com/IdkwhatImD0ing",
};

window.PROJECTS = [
  {
    id: "sentinelai", name: "SentinelAI", year: 2025,
    summary: "Public-safety orchestrator. Detects panic from live audio, drives evacuations in <500ms with a streaming LLM superintendent.",
    tags: ["ai", "voice", "safety", "winner"],
    award: "Best AI/ML — HackDavis 2025",
    accent: "magenta",
    github: "https://github.com/Christopher-Chhim/HackDavis",
    demo: "https://youtu.be/qr3pMPU8lFY",
    stack: ["Whisper", "YAMNet", "vLLM + Llama 3.3", "Twilio", "Retell", "Next.js", "Three.js", "Supabase"],
    role: "Lead AI engineer · audio detection + LLM superintendent",
    long: "In a crisis, panic spreads in seconds but coordinated emergency response takes 9+ minutes — and 70% of casualties happen in the first 5. SentinelAI listens to live audio in commercial spaces, detects screams/alarms/glass breaks, and pushes calm spoken evacuation or lockdown instructions through PA + smart-building IoT in under 500ms. Human operators stay in the loop via a 3D command dashboard.",
  },
  {
    id: "courtvision", name: "CourtVision", year: 2025,
    summary: "2D game footage → 3D Gaussian splat replays. Voice-controlled tactical Q&A for athletes.",
    tags: ["ai", "voice", "3d", "winner"],
    award: "UC Berkeley AI Hackathon 2025",
    accent: "violet",
    github: "https://github.com/aurelisajuan/ai2025",
    demo: "https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/003/502/448/datas/gallery.jpg",
    stack: ["Video Gaussians", "Multimodal LLM", "Vapi Voice API", "WebGL", "VR"],
    role: "Engineer · pipeline + voice agent",
    long: "Standard 2D film is flat. CourtVision reconstructs game footage as time-consistent 3D Gaussian splats, lets athletes rotate, zoom, and slow-mo any moment, and adds a multimodal-LLM voice layer for tactical Q&A — desktop or VR.",
  },
  {
    id: "dispatchai", name: "Dispatch AI", year: 2024,
    summary: "Empathetic 911 co-pilot. Filters by severity, listens for emotion, recommends action — humans always decide.",
    tags: ["ai", "voice", "safety", "winner"],
    award: "Grand Prize — UC Berkeley AI Hackathon 2024",
    accent: "magenta",
    github: "https://github.com/IdkwhatImD0ing/DispatchAI",
    demo: "https://youtu.be/hdpdgxrilQM",
    projectUrl: "https://dispatchai.art3m1s.me/",
    stack: ["Mistral (fine-tuned)", "Twilio", "Hume EVI", "Retell", "Intel Dev Cloud", "Next.js"],
    role: "Co-creator · model fine-tuning + agent runtime",
    long: "82% of US emergency call centers are understaffed. Dispatch AI aggregates 911 calls onto a single platform, classifies severity, extracts location/emotion live, and recommends action. Achieved 80% inference speed-up on Intel IPEX. $25k Berkeley SkyDeck Fund + AI For Good Award.",
  },
  {
    id: "talktuahbank", name: "TalkTuahBank", year: 2024,
    summary: "Phone-only banking for the unbanked. Multi-language voice agent for balances, transfers, and bill pay.",
    tags: ["voice", "fintech", "ai", "winner"],
    award: "Grand + Goldman Sachs — HackUTD 2024",
    accent: "violet",
    github: "https://github.com/aurelisajuan/TalkTuahBank",
    demo: "https://youtu.be/YsH_z1azXSA",
    projectUrl: "https://talktuah.art3m1s.me/",
    stack: ["Retell AI", "OpenAI Swarm", "Pinata (IPFS)", "Next.js", "Tailwind", "ShadCN"],
    role: "Voice + multi-agent backend",
    long: "1.7B adults are unbanked. TalkTuahBank lets anyone with any phone do core banking — balances, transfers, bill pay — in their own language, no smartphone or internet required. Pinata for decentralized data storage; Retell for voice; OpenAI Swarm for dialogue orchestration.",
  },
  {
    id: "adapted", name: "AdaptEd", year: 2024,
    summary: "Live humanoid AI lecturer. Slides rewrite themselves based on what students say back.",
    tags: ["ai", "voice", "education", "winner"],
    award: "Google Challenge — LA Hacks 2024",
    accent: "magenta",
    github: "https://github.com/IdkwhatImD0ing/AdaptEd",
    demo: "https://youtu.be/8o1YJUFBcAw",
    stack: ["Gemini 1.5 Pro", "Fetch.ai", "Hume EVI", "Intel Dev Cloud", "Auth0", "MongoDB"],
    role: "Agent runtime + slide-state engine",
    long: "Half of US university students fall behind because lectures don't adapt. AdaptEd flips it — a humanoid AI lecturer holds real conversation, slides + whiteboard mutate live based on the student's verbal response, and Hume tracks attention & confusion. Multiple agents run side-tasks via Fetch.ai without interrupting the flow.",
  },
  {
    id: "vocalyze", name: "Vocalyze", year: 2025,
    summary: "Banking applications by phone. Speech to filled-in forms, jargon decoded in real time.",
    tags: ["voice", "fintech", "ai", "winner"],
    award: "Letta + Finance — HackMerced X",
    accent: "violet",
    github: "https://github.com/IdkwhatImD0ing/idkwhatthisprojectis",
    demo: "https://youtu.be/s8wF-xCPY04",
    stack: ["Retell AI", "OpenAI GPT-4", "Letta", "Supabase"],
    role: "Conversational architect",
    long: "Loan and credit applications are dense, jargony, and abandoned. Vocalyze handles them by phone — interruptible conversation, jargon-decoder on demand, and the form fills itself.",
  },
  {
    id: "secway", name: "SecWay", year: 2025,
    summary: "Always-on browser companion. Flags overreach, explains it in plain English, one-clicks the fix.",
    tags: ["ai", "security", "winner"],
    award: "DiamondHacks 2025",
    accent: "violet",
    github: "https://github.com/aurelisajuan/DiamondHacks",
    demo: "https://youtu.be/s5A4NHD3QEo",
    stack: ["Gemini 2.5 Turbo", "Google Safe Browsing", "PhishTank", "Chrome Extension API"],
    role: "Privacy UX + AI guidance",
    long: "62% of users never change app or website permissions after first use. SecWay watches every site for overreach, scores it green/orange/red, explains it in plain English, and offers one-click safe defaults. Privacy-first — no backend, no telemetry.",
  },
  {
    id: "slugmeditate", name: "SlugMeditate", year: 2025,
    summary: "Type a calming thought, step into it. Imagen→Veo→Gaussian splats→WebXR meditation worlds.",
    tags: ["ai", "3d", "winner"],
    award: "Gemini + WebXR — CruzHacks 2025",
    accent: "magenta",
    github: "https://github.com/briankhoi/slugmeditate",
    demo: "https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/003/374/704/datas/gallery.jpg",
    stack: ["Imagen 3", "Veo 2", "Gaussian Splatting", "Niantic Studio WebXR", "MusicFX"],
    role: "Pipeline engineer",
    long: "Type 'a peaceful forest at dusk', step inside it. Imagen 3 generates the scene, Veo 2 animates the camera through it, Gaussian Splatting reconstructs it into a navigable 3D world, MusicFX scores the ambience — all in the browser.",
  },
  {
    id: "talktuahduck", name: "TalkTuahDuck", year: 2025,
    summary: "Rubber-duck your notes. Upload messy PDFs and whiteboards, conversation-debug your understanding.",
    tags: ["ai", "voice", "education"],
    accent: "violet",
    github: "https://github.com/AureliaSindhu/sbhacks",
    demo: "https://youtu.be/hlBz5ejdrUc",
    stack: ["Sycamore", "SingleStore", "Retell", "Next.js", "RAG pipeline"],
    role: "RAG + retrieval engineer",
    long: "Active recall beats passive review by ~30%. TalkTuahDuck parses any messy study material — PDFs, photos, handwritten notes — into a vector store, then talks you through it conversationally with grounded citations.",
  },
  {
    id: "tft", name: "TeamFood Tactics", year: 2025,
    summary: "Voice-first food rescue. Bakeries call to log surplus; people in need call to find it.",
    tags: ["voice", "ai", "winner"],
    award: "Sustainability — SpartaHack X",
    accent: "violet",
    github: "https://github.com/aurelisajuan/spartaHacks",
    demo: "https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/003/249/428/datas/gallery.jpg",
    stack: ["Retell AI", "OpenAI", "OpenAI Swarm", "FastAPI", "Supabase"],
    role: "Voice + matching backend",
    long: "60M tons of US food is wasted every year. TeamFood Tactics lets surplus suppliers and dietary-specific consumers connect via a single phone number — no smartphone needed. Dynamic SQL generation matches surplus to need in real time.",
  },
  {
    id: "splatnft", name: "SplatNFT", year: 2024,
    summary: "Turn personal video into interactive 3D NFTs. Solana-minted, Anyone Protocol-stored.",
    tags: ["3d", "web3", "winner"],
    award: "SolanaU — SoCal Tech Week",
    accent: "magenta",
    github: "https://github.com/KevinWu098/SplatNFT",
    demo: "https://d112y698adiu2z.cloudfront.net/photos/production/software_photos/003/130/048/datas/gallery.jpg",
    stack: ["Solana", "Anyone Protocol", "Gaussian Splatting", "Next.js", "Node.js"],
    role: "Frontend + minting flow",
    long: "Convert any personal video into an interactive 3D Gaussian-splat representation, then mint it as an NFT on Solana via the Anyone Protocol. End-to-end: upload → splat → preview → mint → gallery.",
  },
  {
    id: "instarizz", name: "InstaRizz", year: 2024,
    summary: "Ray-Ban smart glasses + Claude. Live face-recognition pickup-line generator. Spicy. Provocative.",
    tags: ["ai", "wearable"],
    accent: "magenta",
    github: "https://github.com/coderkai03/AI-ATL-2024",
    demo: "https://youtu.be/xjMcK34BBu4",
    stack: ["Ray-Ban Meta", "OpenCV", "Magic Loops", "Claude", "Perplexity"],
    role: "Pipeline + ethics framing",
    long: "Equal parts demo and provocation: Ray-Ban smart glasses live-stream to Instagram, OpenCV grabs frames, a custom classifier matches consenting participants, and a Magic Loops + Claude chain produces a bio + three pickup lines in seconds. Built deliberately to spark a discussion about wearable-AI ethics.",
  },
];

window.HACKATHONS = [
  { name: "HackDavis", year: 2025, award: "Best AI/ML" },
  { name: "UC Berkeley AI 2025", year: 2025, award: "Track Winner" },
  { name: "DiamondHacks", year: 2025, award: "Winner" },
  { name: "CruzHacks", year: 2025, award: "Gemini + WebXR" },
  { name: "HackMerced X", year: 2025, award: "Letta + Finance" },
  { name: "SpartaHack X", year: 2025, award: "Sustainability" },
  { name: "SB Hacks XI", year: 2025, award: "Featured" },
  { name: "HackUTD 2024", year: 2024, award: "Grand Prize + Goldman Sachs" },
  { name: "UC Berkeley AI 2024", year: 2024, award: "Grand Prize $25k" },
  { name: "LA Hacks", year: 2024, award: "Google Challenge" },
  { name: "AI ATL", year: 2024, award: "Featured" },
  { name: "SoCal Tech Week", year: 2024, award: "SolanaU" },
];

window.EDUCATION = [
  {
    school: "USC",
    full: "University of Southern California",
    degree: "M.S. Computer Science — AI Specialization",
    when: "Aug 2023 — May 2025",
    detail: "Graduate-level ML, applied AI, agentic systems. Built voice-first products throughout.",
    logo: "assets/usc.png",
  },
  {
    school: "UCSC",
    full: "UC Santa Cruz",
    degree: "B.S. Computer Science",
    when: "Sep 2020 — Mar 2023",
    detail: "Finished a 4-year program in 2.5 years. Caught the hackathon bug.",
    logo: "assets/ucsc.png",
  },
  {
    school: "Lynbrook",
    full: "Lynbrook High School",
    degree: "College Prep",
    when: "2016 — 2020",
    detail: "South Bay. First wrote code here.",
    logo: "assets/lynbrook.png",
  },
];

window.EXPERIENCE = [
  {
    when: "2024 — Now",
    role: "Software Engineer",
    where: "Voice AI · Los Angeles",
    body: "Building production voice agents end-to-end. Latency budgets in the hundreds of ms, real-time tool-use, multi-turn state.",
    badge: "Now",
  },
  {
    when: "2023 — 2024",
    role: "ML Engineer Intern",
    where: "Major AI Lab",
    body: "Fine-tuned and shipped multi-modal models. Owned eval infrastructure. Publication-quality experiments on tight cycles.",
  },
  {
    when: "2022 — 2023",
    role: "Software Engineer Intern",
    where: "Big Tech",
    body: "Backend systems at scale — high-throughput services, observability, on-call rotation.",
  },
  {
    when: "2020 — 2023",
    role: "Hackathon Mainstay",
    where: "12+ wins across the West Coast",
    body: "Shipped a startup-grade product every weekend. Most of the projects on this page started here.",
  },
];

window.SKILLS_LINE = [
  { w: "I build" },
  { w: "voice-first" }, { w: "agents", tag: true },
  { w: "that ship in" },
  { w: "weekends,", tag: true },
  { w: "win" },
  { w: "grand prizes,", tag: true },
  { w: "and run in" },
  { w: "production." }, { w: "I care about" },
  { w: "latency,", tag: true },
  { w: "human-in-the-loop", tag: true },
  { w: "control, and the" },
  { w: "quiet craft", tag: true },
  { w: "of making AI feel like a" },
  { w: "real" }, { w: "product." },
];

window.PERSONAL_FACTS = [
  { icon: "✦", line: "Finished a 4-year CS degree in <b>2.5 years</b>." },
  { icon: "✦", line: "Won my first hackathon at <b>17</b>. Haven't slowed down." },
  { icon: "✦", line: "Speaks <b>Mandarin and English</b>; building agents in both." },
  { icon: "✦", line: "If I'm not coding, I'm probably <b>climbing</b> or chasing good coffee." },
  { icon: "✦", line: "Believe the next billion users will <b>talk to software</b>, not click it." },
];
