#!/usr/bin/env bash
# Pulls runtime secrets from GCP Secret Manager into server/.env.
# Run after `gcloud auth login`. Idempotent — safe to re-run any time.

set -euo pipefail

PROJECT="${GCP_PROJECT:-spiritual-storm-469704-n2}"
SECRETS=(OPENAI_API_KEY RETELL_API_KEY PINECONE_API_KEY OBFUSCATED_WS_PATH)
# Pulled when present. The server runs without them (see app_helpers.py).
OPTIONAL_SECRETS=(PUSHER_SECRET)
# Kept, never pulled. FireTrace keys are per environment: the production key
# lives in Secret Manager for deploy.sh alone, and the development key is
# typed into this file once. A re-pull carries it over instead of wiping it,
# and never replaces it with the production one.
KEEP_FROM_ENV=(FIRETRACE_API_KEY)
BS='\'  # one backslash, kept in a variable so no ${var//…} replacement has to spell it

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

if ! command -v gcloud >/dev/null 2>&1; then
  echo "✗ gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install" >&2
  exit 1
fi

ACTIVE="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null || true)"
if [[ -z "$ACTIVE" ]]; then
  echo "✗ No active gcloud account. Run: gcloud auth login" >&2
  exit 1
fi

echo "▶ Project: $PROJECT  ·  Account: $ACTIVE"

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "  ↻ existing .env backed up to .env.bak"
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by server/scripts/pull-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: GCP Secret Manager (project $PROJECT)"
  echo "# Do not commit — gitignored."
  echo
} >"$TMP"

write_env_line() {
  local name="$1" val="$2" escaped ch
  # Single-quote the value: bash and python-dotenv both read that literally.
  # A value holding a single quote (or a doubled backslash, which python-dotenv
  # would collapse) goes in double quotes instead. Both loaders agree on \\ and
  # \" there, whereas python-dotenv does not understand the shell's 'a'\''b'
  # trick and drops the key with a parse warning.
  if [[ "$val" != *"'"* && "$val" != *'\\'* ]]; then
    printf "%s='%s'\n" "$name" "$val" >>"$TMP"
  else
    escaped="$val"
    for ch in "$BS" '"' '$' '`'; do  # backslash first so the others are not re-escaped
      escaped="${escaped//"$ch"/"$BS$ch"}"
    done
    printf '%s="%s"\n' "$name" "$escaped" >>"$TMP"
    if [[ "$val" == *'$'* || "$val" == *'`'* ]]; then
      echo "  ⚠ $name: python-dotenv keeps the backslash before \$ and \` in a double-quoted value; check $ENV_FILE by hand" >&2
    fi
  fi
}

for name in "${SECRETS[@]}"; do
  if ! val="$(gcloud secrets versions access latest --secret="$name" --project "$PROJECT" 2>/dev/null)"; then
    echo "✗ Failed to read secret '$name'. Does your account have secretmanager.secretAccessor on it?" >&2
    exit 1
  fi
  write_env_line "$name" "$val"
  echo "  ✓ $name"
done

for name in "${OPTIONAL_SECRETS[@]}"; do
  if val="$(gcloud secrets versions access latest --secret="$name" --project "$PROJECT" 2>/dev/null)"; then
    write_env_line "$name" "$val"
    echo "  ✓ $name"
  elif [[ -f "$ENV_FILE" ]] && existing="$(grep -m1 "^${name}=" "$ENV_FILE")"; then
    # Not in Secret Manager (yet), but typed into .env by hand: keep it.
    printf "%s\n" "$existing" >>"$TMP"
    echo "  ↻ $name kept from existing .env (not readable in Secret Manager)"
  else
    echo "  – $name not readable in Secret Manager (optional; skipped)"
  fi
done

for name in "${KEEP_FROM_ENV[@]}"; do
  if [[ -f "$ENV_FILE" ]] && existing="$(grep -m1 "^${name}=" "$ENV_FILE")"; then
    printf "%s\n" "$existing" >>"$TMP"
    echo "  ↻ $name kept from existing .env"
  else
    echo "  – $name not set (optional; add it to $ENV_FILE by hand)"
  fi
done

mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "▶ Wrote $ENV_FILE"
