#!/usr/bin/env bash
# Pulls runtime secrets from GCP Secret Manager into server/.env.
# Run after `gcloud auth login`. Idempotent — safe to re-run any time.

set -euo pipefail

PROJECT="${GCP_PROJECT:-spiritual-storm-469704-n2}"
SECRETS=(OPENAI_API_KEY RETELL_API_KEY PINECONE_API_KEY OBFUSCATED_WS_PATH)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

if ! command -v gcloud >/dev/null 2>&1; then
  echo "✗ gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install" >&2
  exit 1
fi

ACTIVE="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null || true)"
if [[ -z "$ACTIVE" ]]; then
  echo "✗ No active gcloud account. Run: gcloud auth login" >&2
  exit 1
fi

echo "▶ Project: $PROJECT  ·  Account: $ACTIVE"

if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "  ↻ existing .env backed up to .env.bak"
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by server/scripts/pull-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: GCP Secret Manager (project $PROJECT)"
  echo "# Do not commit — gitignored."
  echo
} >"$TMP"

for name in "${SECRETS[@]}"; do
  if ! val="$(gcloud secrets versions access latest --secret="$name" --project "$PROJECT" 2>/dev/null)"; then
    echo "✗ Failed to read secret '$name'. Does your account have secretmanager.secretAccessor on it?" >&2
    exit 1
  fi
  # Single-quote the value; escape any embedded single quote as '\''
  escaped="${val//\'/\'\\\'\'}"
  printf "%s='%s'\n" "$name" "$escaped" >>"$TMP"
  echo "  ✓ $name"
done

mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "▶ Wrote $ENV_FILE"
